version: "3"

services:
  learn-ocaml-server:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - TZ=${TZ}
    env_file:
      - .env
    links:
      - "nodejs:nodeserver"
    ports:
      - "0.0.0.0:80:${LEARNOCAML_PORT}"
    expose:
      - "8080"
    volumes:
      - ${REPOSITORY}:/repository:ro
      - learn-ocaml-sync:/sync

  mongodb:
    image: mongo:latest
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: learn-ocaml-code
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/etc/mongod.conf
      - mongodb_data_container:/docker-entrypoint-initdb.d/
      - mongodb_data_container:/data/db/
      - mongodb_data_container:/var/log/mongodb/


  nodejs:
    build: 
      context: node/
    ports: 
      - "0.0.0.0:8000:8000"
    environment:
      - PORT=8000
      - DB_CONN=mongodb://mongodb:27017/learn-ocaml-code
      - COMP_COLLECTION=compileCode
      - EVAL_COLLECTION=evalCode
    volumes:
      - ./node:/node/app
      - node_modules:/node/app/node_modules
    depends_on:
      - mongodb


volumes:
  repository:
  sync:
  learn-ocaml-sync:
  mongodb_data_container:
  node_modules:
